### ISSUE TITLE
multi language pls

### ISSUE THREAD

**Issue by qysaber** [michael-arawole/synote#1]
multi language pls,if not en,  the charactor will display as "???"

**Comment by michaelthedev** [comment]
Hi, you need to change your database collation to utf8 to support multiple languages

If, you've already imported the database file, you should try running this SQL code
`ALTER TABLE user_notes CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;`

OR
I've updated the database export file in the repo to utf8. You can import the updated one into your database instead
